### ISSUE TITLE
Better Message-ID handling

### ISSUE THREAD

**Issue by csaftoiu** [csaftoiu/slack-email-digest#10]
Right now messages ids vary only by date. They don't vary by slack group name or channel. They should, so separate threads are kept separate.

`slack.team.info().body['id']` gives the unique team id.

**Comment by srid** [comment]
Message-ID can be computed using the combination of:
- Date
- Slack group name (retrievable from Slack API)
- Slack channel (passed as config var / docopt)

Therefore, this is not necessarily blocked by #2?

**Comment by csaftoiu** [comment]
How do I get the slack group name from the API? I was looking for that route but couldn't find it.

**Comment by srid** [comment]
Maybe this? https://api.slack.com/methods/team.info

**Comment by csaftoiu** [comment]
Ah yes! I think I had seen it but for some reason thought it was something else. Maybe I confused it with user groups.

Indeed, in that case this isn't blocked by #2.

**Comment by csaftoiu** [comment]
Resolved by #18.
