### ISSUE TITLE
Meta info in footer or header

### ISSUE THREAD

**Issue by srid** [csaftoiu/slack-email-digest#2]
Include meta info like the following in the header of footer of every digest email:
- Link to joining Slack conversation for lurkers: https://actualfreedom-slackin.herokuapp.com
- Disclaimers? Policy for referencing?

**Comment by csaftoiu** [comment]
In #19, I added a sub-header like this:

![image](https://cloud.githubusercontent.com/assets/43113/17467389/9ab190d4-5cd2-11e6-944a-b2dd74cf8877.png)

May be worth adding a policy in the footer saying to the effect that anonymized quotes can be pasted elsewhere, but don't use names without permission. Something like this. Or may be fine as-is

**Comment by srid** [comment]
> May be worth adding a policy in the footer

Perhaps just link to a wiki page here, that goes into detail about Slack policy use.
