### ISSUE TITLE
Linked gifs and images

### ISSUE THREAD

**Issue by srid** [csaftoiu/slack-email-digest#3]
Slack embeds gifs and images automatically in the channel. Will this be the case for digest emails?

**Comment by csaftoiu** [comment]
:+1:, this is eminently doable. I won't do it for files or uploaded images, since those are accessible only with a login, but for linked images it should be fine.

**Comment by csaftoiu** [comment]
It is done. Only thing is, it doesn't paste the image in-line in the message, just afterwards, but good enough for now I think.
