### ISSUE TITLE
Quote linked messages

### ISSUE THREAD

**Issue by srid** [csaftoiu/slack-email-digest#5]
For example:

```
srid: @solvann: example here: https://actualfreedom.slack.com/archives/general/p1470071346001458
```

In Slack, that embeds the linked message. But in the digest no such thing happens. Would be nice to do it though.

**Comment by csaftoiu** [comment]
Hmm will have to see about this one, may be slightly tricky. But still do-able I'm sure

**Comment by csaftoiu** [comment]
Ah this ended up being solved when I added attachments in general.
