### ISSUE TITLE
Assign same month digests to same email thread

### ISSUE THREAD

**Issue by srid** [csaftoiu/slack-email-digest#9]
Assign digests from the same month to the single conversation thread so they appear 'grouped' in the Yahoo! Group.

The chief benefit of doing this is that it will lead to less cluttering of Yahoo! Group message archive page, when viewed by-thread basis.

**Comment by csaftoiu** [comment]
Hmm any thoughts on how to do this? First thought is to change them to all have the same subject, e.g. "Slack Digests for August 2016", but I think it'd be nicer to keep the subject lines distinct.

**Comment by srid** [comment]
The subject can remain distinct. Have you not noticed how Yahoo! Group puts replies in the same thread despite changing their subject?

**Comment by csaftoiu** [comment]
Resolved via SMTP - wil be threaded together as long as the previous day's message has already been sent.
